type Book {
	id: ID
	designation: String
	description: String
}

input FindBookByIdInput {
	id: ID
}

input CreateBookInput {
	designation: String
	description: String
}

type Query {
	findBooks: [Book]
	findBookById(input: FindBookByIdInput): Book
}

type Mutation {
	createBook(input: CreateBookInput): Book
}
